valor1 = input("Digite o primeiro valor: ")
valor2 = input("Digite o segundo valor: ")
soma = float(valor1) + float(valor2)
print("A soma é: {}" .format(soma))
subtracao = float(valor1) - float(valor2)
print("A subtração é: {}" .format(subtracao))
divisao = float(valor1) / float(valor2)
print("A divisao é: {}" .format(divisao))
multiplicacao = float(valor1) * float(valor2)
print("A multiplcacao é: {}" .format(multiplicacao))
potencia = float(valor1) ** float(valor2)
print("A potencia é: {}" .format(potencia))
